budproj/business

src/app/key-result-views/controller.ts
src/app/key-result-views/dto.ts
src/app/key-result-views/index.ts
src/app/key-result-views/module.ts
src/app/key-result-views/service.ts
src/app/key-results/controller.ts
src/app/key-results/decorators.ts
src/app/key-results/dto.ts
src/app/key-results/interceptors.ts
src/app/key-results/module.ts
src/app/key-results/service.ts
src/app/module.ts
src/app/providers.ts
src/bootstrap/index.ts
src/domain/objective-aggregate/key-result-view/dto.ts
src/domain/objective-aggregate/key-result-view/entities.ts
src/domain/objective-aggregate/key-result-view/repository.ts
src/domain/objective-aggregate/key-result-view/service.ts
src/domain/objective-aggregate/service.ts
src/errors/index.ts
src/errors/railway-error.ts
src/errors/resource-not-allowed.ts
tsconfig.json

This PR adds the basic `GET`, `POST` and `PATCH` logic to Key Result Views resource, alongside with `Errors` and some minor improvements.

Feature: Key Result Views Patch

---

src/app/graphql/key-result-view/models.ts
src/app/graphql/key-result-view/resolver.ts
src/app/graphql/key-result/models.ts
src/domain/key-result/dto.ts
src/domain/key-result/entities.ts
src/migrations/1606314925017-AddFormatToKeyResult.ts

This feature creates a possible format for our key results.

Feature: Key Result Format

---

src/app/graphql/company/models.ts
src/app/graphql/cycle/models.ts
src/app/graphql/key-result/models.ts
src/app/graphql/key-result/report/confidence/models.ts
src/app/graphql/key-result/report/models.ts
src/app/graphql/key-result/report/progress/models.ts
src/app/graphql/objective/models.ts
src/app/graphql/team/models.ts
src/app/graphql/user/models.ts
src/app/graphql/user/view/key-result/models.ts

This PR fixes our GraphQL model names and add some descriptions.

Fix: GraphQL Models

---

src/app/graphql/company/models.ts
src/app/graphql/cycle/models.ts
src/app/graphql/key-result/models.ts
src/app/graphql/key-result/report/confidence/models.ts
src/app/graphql/key-result/report/models.ts
src/app/graphql/key-result/report/progress/models.ts
src/app/graphql/key-result/report/resolver.ts
src/app/graphql/objective/models.ts
src/app/graphql/team/models.ts
src/app/graphql/user/models.ts
src/app/graphql/user/view/key-result/models.ts

This PR fix some errors regarding our check-in feature

Bugfix: Popover integration

---

Dockerfile
package.json
waypoint.hcl

This PR moves to a Dockerfile to improve our deployment structure.

Feature: Dockerfile

---

manifests/develop/deployment.yaml

This PR refactors our Authz Tenants

Refactor: Authz Tenants

---

src/app/graphql/factory.ts
src/bootstrap/index.ts
src/config/gql/config.ts
src/config/gql/index.ts
src/config/gql/types.ts

Bugfix: CORS

---

src/app/graphql/service.ts

This PR fix our bug with the constraint selector at policies.

Bugfix: Constraint Selector

---

manifests/develop/deployment.yaml
src/config/gql/config.ts
src/config/gql/types.ts
src/domain/key-result/report/progress/service.ts

This PR fixes GraphQL Playground on develop.

Bugfix: GraphQL Playground

---

src/app/graphql/factory.ts

This PR fixes GraphQL Playground on Develop.

Bugfix: GraphQL Playground on Develop

---

src/app/graphql/user/resolver.ts

This PR adds a resolver to return current user data.

Feature: Me

---

src/domain/key-result/service.ts
src/domain/team/service.ts

This PR fixes the calculation of team current progress by considering root team key results. Also, it fixes the calculation of the current progress itself.

Bugfix: Team current progress

---

src/app/graphql/key-result/report/models.ts
src/app/graphql/key-result/report/resolver.ts
src/domain/key-result/report/progress/entities.ts
src/domain/key-result/report/service.ts
src/migrations/1608765362618-RemovesProgressReportUniqueConstraint.ts

This PR fixes some bugs that were preventing users from creating check-ins.

Bugfix: Check-in duplicates

---

package.json
src/database/actions/index.ts
src/database/actions/run-queries-from-file.ts
src/database/environments/develop/load-dump.ts
src/database/environments/local/load-dump.ts
src/database/environments/production/load-sandbox.ts
src/database/environments/production/sandbox-account/cycles.sql
src/database/environments/production/sandbox-account/key-results.sql
src/database/environments/production/sandbox-account/objectives.sql
src/database/environments/production/sandbox-account/teams.sql
src/database/environments/production/sandbox-account/teams_users_user.sql
src/database/environments/production/sandbox-account/users.sql

This PR adds the production sandbox content to our database dumps.

Chore: Database - Production Sandbox content

---

src/app/graphql/user/models.ts
src/app/graphql/user/resolver.ts
src/app/graphql/user/service.ts
src/domain/user/service.ts

This PR adds the user full name field

Feature: User full name

---

src/app/graphql/user/models.ts
src/app/graphql/user/resolver.ts
src/app/graphql/user/service.ts
src/domain/user/service.ts

This PR adds the user fullname

Feature: User fullname

---

manifests/stable/deployment.yaml
src/domain/user/view/key-result/service.ts

This PR fixes the Key Result View that was showing KRs in it's rank that were not from the user.

Bugfix: Key Result View rank listing

---

.eslintrc
package-lock.json
package.json
src/domain/key-result/report/confidence/service.ts
src/domain/key-result/report/progress/service.ts
src/domain/key-result/repository.ts
src/domain/key-result/service.ts

This PR solves some minor bugs and issue that I've created yesterday.

Hotfix: Minor bugs

---

src/domain/user/view/key-result/service.ts

This PR fixes the issue that was mixing the key result users views

Bugfix: Key Result View was mixing users views

---

src/domain/cycle/repository.ts
src/domain/key-result/report/confidence/repository.ts
src/domain/key-result/report/progress/repository.ts
src/domain/key-result/repository.ts
src/domain/objective/repository.ts
src/domain/repository.ts
src/domain/team/repository.ts
src/domain/user/repository.ts
src/domain/user/view/key-result/repository.ts

This PR fixes some missed constraints regarding our team and owns scopes.

Bugfix: Missed constraints

---

src/app/authz/god-user.ts
src/database/environments/develop/dump.sql
src/domain/key-result/report/confidence/module.ts
src/domain/key-result/report/confidence/service.ts
src/domain/key-result/report/progress/service.ts
src/domain/key-result/report/service.ts
src/domain/key-result/service.ts

This PR allows check-ins to be created only with comments too.

Feature: Allow only comment check-ins

---

manifests/canary/canary-deployment.yaml
manifests/stable/deployment.yaml
src/app/authz/strategy.ts
src/database/environments/develop/dump.sql

This PR does some minor go live adjustments.

Bugfix: Minor go live adjustments

---

src/app/graphql/key-result/models.ts

This PR fixes some issues created by our timeline canary release.

Bugfix: Timeline canary release

---

src/app/graphql/key-result/check-in/models.ts
src/app/graphql/key-result/check-in/resolver.ts
src/app/graphql/key-result/models.ts
src/app/graphql/key-result/resolver.ts
src/domain/key-result/service.ts

This PR changes some names in our key-result application layer.

Refactor: Key Result Naming

---

features/key-result.gql
features/objective.gql
features/team.gql
src/app/graphql/objective/models.ts
src/app/graphql/objective/resolver.ts
src/app/graphql/team/models.ts
src/app/graphql/team/resolver.ts
src/domain/entity.ts
src/domain/key-result/check-in/service.ts
src/domain/objective/service.ts
src/domain/team/module.ts
src/domain/team/ranking.ts
src/domain/team/service.ts

This PR adds the teams overview to our dashboard.

Feature: Add teams overview to dashboard

---

src/app/authz/god-user.ts
src/app/authz/service.ts
src/app/authz/types.ts
src/app/graphql/authz/guards.ts
src/app/graphql/authz/interceptors.ts
src/app/graphql/authz/resolver.ts
src/app/graphql/cycle/resolver.ts
src/app/graphql/resolver.ts
src/domain/cycle/service.ts

This PR starts the cycle ordering feature.

(Partial) Feature: Cycle ordering

---

src/app/graphql/key-result/check-in/models.ts
src/app/graphql/key-result/check-in/resolver.ts
src/domain/key-result/service.ts

This PR adds the absolute value increase to the check-in data

Feature: Absolute value increase in check-in

---

src/app/graphql/user/models.ts
src/app/graphql/user/resolver.ts
src/database/migrations/1614113443573-AddsSettingsToUser.ts
src/database/migrations/1614115061168-UpdatesUserAboutSectionToLongText.ts
src/domain/user/dto.ts
src/domain/user/entities.ts

This PR adds basic structure for user settings.

Feature: User settings

---

src/app/graphql/key-result/check-in/resolver.ts
src/app/graphql/key-result/models.ts
src/database/migrations/1615988871285-UpdatesKeyResultCheckInFromProgressToValue.ts
src/domain/key-result/check-in/dto.ts
src/domain/key-result/check-in/entities.ts
src/domain/key-result/check-in/service.ts
src/domain/key-result/service.ts
src/domain/objective/service.ts
src/domain/team/service.ts

Refactor: Check In Value

---

src/app/graphql/cycle/resolver.ts
src/domain/cycle/service.ts

Bugfix: Child Cycles

---

src/database/migrations/1616010887736-RemoveKeyResultCustomList.ts

This PR removes the Key Result Custom List table.

Chore: Removes Key Result Custom List

---

.devcontainer/docker-compose.yaml
src/config/app/config.ts
tsconfig.build.json

This PR fixes some typescript bugs

Bugfix: Fix Typescript

---

src/interface/graphql/authorization/resolvers/guarded-node.resolver.ts
src/interface/graphql/enums/sorting.enum.ts
src/interface/graphql/modules/key-result/check-in/key-result-check-in.resolver.ts
src/interface/graphql/modules/key-result/check-in/objects/key-result-check-in-input.object.ts
src/interface/graphql/modules/key-result/comment/key-result-comment.resolver.ts
src/interface/graphql/modules/key-result/comment/objects/key-result-comment-input.object.ts
src/interface/graphql/modules/key-result/key-result.resolver.ts
src/interface/graphql/modules/user/objects/user-input.object.ts
src/interface/graphql/modules/user/user.resolver.ts
src/interface/graphql/objects/order-node.object.ts
src/interface/graphql/relay/objects/page-info.object.ts
src/interface/graphql/relay/relay.provider.ts
src/interface/graphql/requests/connection-filters.request.ts
src/interface/graphql/upload/upload.provider.ts

This PR fixes some bugs that I've found while integrating the new GraphQL interface with our front-end.

Bugfix: Front-end integration

---

src/core/modules/team/ranking.provider.ts

This PR fixes the team ranking order.

Bugfix: Team ranking order

---

src/interface/graphql/modules/key-result/key-result.resolver.ts
src/interface/graphql/modules/key-result/objects/key-result-input.object.ts
src/interface/graphql/modules/key-result/requests/key-result-update.request.ts

This PR adds the ability to update a given key-result.

Feature: Update Key Result

---

src/core/core.repository.ts
src/core/entity.provider.ts
src/core/modules/cycle/cycle.repository.ts
src/core/modules/key-result/check-in/key-result-check-in.repository.ts
src/core/modules/key-result/comment/key-result-comment.repository.ts
src/core/modules/key-result/key-result.repository.ts
src/core/modules/objective/objective.repository.ts
src/core/modules/team/team.repository.ts
src/core/modules/user/user.repository.ts
src/interface/graphql/modules/user/objects/user-order-input.object.ts
src/interface/graphql/modules/user/requests/user-filters.request.ts
src/interface/graphql/objects/default-order.object.ts
src/interface/graphql/objects/order.object.ts
src/interface/graphql/requests/connection-filters.request.ts

This pull request fixes the core sorting feature.

Bugfix: Core Sorting

---

src/adapters/authorization/access-control.adapter.ts
src/interface/graphql/modules/key-result/check-in/key-result-check-in.access-control.ts
src/interface/graphql/modules/key-result/check-in/key-result-check-in.resolver.ts
src/interface/graphql/modules/key-result/comment/key-result-comment.access-control.ts
src/interface/graphql/modules/key-result/comment/key-result-comment.resolver.ts
src/interface/graphql/modules/key-result/key-result.access-control.ts
src/interface/graphql/modules/key-result/key-result.resolver.ts

Bugfix: Fixes auth issue

---

.idea/vcs.xml
src/core/modules/key-result/key-result.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-key-result-comment.command.ts
src/interface/graphql/modules/key-result/access-control/key-result-comment.access-control.ts

This PR fixes some issues with comment policy

Bugfix: Fixing comment policy

---

.env
src/config/aws/aws-environment.schema.ts
src/config/aws/aws.config.ts
src/config/aws/aws.interface.ts
src/infrastructure/aws/ses/ses.provider.ts
src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

This PR improves our comment notification

Feature: Comment notification improvements

---

src/core/ports/commands/get-key-result-check-in-delta.ts

This PR fixes the missing symbols in our delta ports.

Bugfix: Missing symbols

---

src/core/modules/key-result/key-result.provider.ts

This PR fixes the reversed check-in

Bugfix: Fixes reversed check-in

---

src/core/entity.provider.ts
src/core/modules/key-result/key-result.provider.ts
src/core/modules/objective/objective.repository.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/delete-key-result.command.ts
src/interface/graphql/modules/key-result/access-control/base.access-control.ts
src/interface/graphql/modules/key-result/comment/key-result-comment.resolver.ts
src/interface/graphql/modules/key-result/key-result.resolver.ts
src/interface/graphql/requests/node-delete.request.ts

Feature: Remove key-result

---

src/core/modules/key-result/check-in/key-result-check-in.provider.ts
src/core/modules/key-result/check-in/key-result-check-in.repository.ts
src/core/modules/key-result/comment/key-result-comment.provider.ts
src/core/modules/key-result/comment/key-result-comment.repository.ts
src/core/modules/key-result/key-result.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/delete-objective.command.ts
src/interface/graphql/modules/objective/objective.resolver.ts

This PR adds the Remove Objective feature.

Feature: Remove Objective

---

src/core/interfaces/status.interface.ts
src/core/modules/cycle/cycle.provider.ts
src/core/modules/key-result/key-result.module.ts
src/core/modules/key-result/key-result.provider.ts
src/core/modules/objective/objective.module.ts
src/core/modules/objective/objective.provider.ts
src/core/ports/commands/base-status.command.ts
src/core/ports/commands/get-cycle-status.command.ts
src/core/ports/commands/get-key-result-check-in-status.command.ts
src/core/ports/commands/get-key-result-status.command.ts
src/core/ports/commands/get-objective-status.command.ts
src/core/ports/commands/get-team-status.command.ts
src/interface/graphql/modules/key-result/check-in/key-result-check-in.resolver.ts
src/interface/graphql/modules/key-result/comment/key-result-comment.resolver.ts
src/interface/graphql/objects/status.object.ts

This PR enables our users to check previous cycles in their team page

Feature: Team Page Time Machine

---

.devcontainer/devcontainer.json
.env
.vscode/launch.json
src/config/aws/aws-environment.schema.ts
src/config/aws/aws.config.ts
src/config/aws/aws.interface.ts
src/infrastructure/aws/ses/ses.provider.ts
src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

This PR updates the required logic to our new comment e-mail. It also creates a debug logic to allow us debugging SES sending.

Feature: New comment e-mail

---

.vscode/settings.json
src/adapters/confidence-tag/confidence-tag.adapters.ts
src/adapters/confidence-tag/confidence-tag.constants.ts
src/adapters/email/types/metadata.type.ts
src/core/modules/team/team.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-key-result-confidence-color.command.ts
src/core/ports/commands/get-team-members.command.ts
src/infrastructure/aws/ses/ses.provider.ts
src/infrastructure/notification/channels/email/email.channel.ts
src/infrastructure/notification/notifications/created-key-result-check-in.notification.ts
src/infrastructure/notification/notifications/notification.factory.ts
src/infrastructure/notification/types/recipient.type.ts
src/interface/graphql/modules/team/requests/team-members-filters.request.ts
src/interface/graphql/modules/team/team.resolver.ts

This PR creates the required integrations and data fetching to dispatch the barrier e-mail.

Feature: Notify Key Result with barrier

---

src/core/modules/user/user.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-users-by-ids.command.ts
src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

Feat: mention notification

---

src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

fix(infra/notification/created-comment): regex

---

src/core/modules/user/user.provider.ts
src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

Fix: notification mention QA

---

src/infrastructure/notification/notifications/created-key-result-comment.notification.ts

fix(infra/notification/created-comment): missing team gender properties

---

src/interface/graphql/modules/key-result/access-control/key-result-check-in.access-control.ts
src/interface/graphql/modules/key-result/access-control/key-result-check-mark.access-control.ts

Bugfix: support team and check marks

---

.env
src/adapters/credentials/credentials.adapter.ts
src/adapters/credentials/credentials.interface.ts
src/config/authz/authz-environment.schema.ts
src/config/authz/authz.config.ts
src/config/authz/authz.interface.ts
src/config/authz/authz.provider.ts
src/core/modules/user/user.interface.ts
src/core/modules/user/user.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/create-user.command.ts
src/infrastructure/authz/providers/client.provider.ts
src/infrastructure/authz/providers/credentials.provider.ts
src/interface/graphql/modules/team/connections/team-users/team-users.resolver.ts
src/interface/graphql/modules/team/team.module.ts
src/interface/graphql/modules/user/objects/user-create-input.object.ts
src/interface/graphql/modules/user/objects/user-update-input.object.ts
src/interface/graphql/modules/user/requests/user-create.request.ts
src/interface/graphql/modules/user/requests/user-update.request.ts
src/interface/graphql/modules/user/user.access-control.ts
src/interface/graphql/modules/user/user.module.ts
src/interface/graphql/modules/user/user.resolver.ts

This feature adds all the required structure to create new users.

Feat: Create User

---

src/core/modules/team/team.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/create-team.command.ts
src/core/ports/commands/update-team.command.ts
src/interface/graphql/modules/team/objects/team-create-input.object.ts
src/interface/graphql/modules/team/requests/team-create.request.ts
src/interface/graphql/modules/team/team.access-control.ts
src/interface/graphql/modules/team/team.module.ts
src/interface/graphql/modules/team/team.resolver.ts

Adds create team mutation.
* https://github.com/budproj/execution-mode/pull/196

Feat: create team

---

src/infrastructure/notification/notifications/created-key-result-check-mark.notification.ts

bugfix: checkmark assign

---

src/infrastructure/notification/notifications/created-key-result-check-mark.notification.ts
src/infrastructure/notification/notifications/notification.factory.ts
src/interface/graphql/modules/key-result/check-mark/key-result-check-mark.resolver.ts

bugfix(infra/notification/assigned-checkmark): send email

---

src/infrastructure/orm/migrations/1644951575317-RequiredAssigneeToCheckMark.ts

feat(infra/migrations): change checkmark assignee as required

---

src/core/modules/key-result/check-mark/key-result-check-mark.provider.test.ts
src/core/modules/key-result/check-mark/key-result-check-mark.provider.ts
src/core/modules/key-result/key-result.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-check-list-for-key-result.command.ts
src/core/ports/commands/get-checklist-of-user.ts
src/core/ports/commands/get-key-result-check-in-delta.command.ts
src/core/ports/commands/get-key-results-containing-user-checklist.ts
src/infrastructure/orm/migrations/1644951575317-RequiredAssigneeToCheckMark.ts
src/interface/graphql/modules/key-result/check-mark/requests/key-result-check-mark-filters.request.ts
src/interface/graphql/modules/key-result/key-result.resolver.ts
src/interface/graphql/modules/user/requests/user-key-results.request.ts
src/interface/graphql/modules/user/user.resolver.ts

Adds support do view all check marks assigned to the user.
- budproj/execution-mode#225

Feat: my things screen

---

manifests/canary/canary-deployment.yaml
manifests/stable/deployment.yaml

bugfix(manifests): add sentry environment variables

---

manifests/ingress-route.yaml

bugfix(manifests/ingres-route): use tls 1.2 or above

---

src/core/modules/objective/objective.provider.ts
src/core/ports/commands/get-objectives-and-key-results-quantities.command.ts

fix(objective-board): fixing method of objectives quantity

---

.dockerignore
.github/workflows/deploy-to-canary.yml
Dockerfile
bin/install.sh
package.json

CI: deploy to canary

---

src/core/ports/commands/command.factory.ts
src/core/ports/commands/delete-cycle.command.ts
src/core/ports/commands/update-cycle.command.ts
src/interface/graphql/modules/cycle/access-control/cycle.access-control.ts
src/interface/graphql/modules/cycle/cycle.module.ts
src/interface/graphql/modules/cycle/cycle.resolver.ts
src/interface/graphql/modules/cycle/inputs/cycle.input.ts
src/interface/graphql/modules/cycle/requests/cycle-create-request.ts
src/interface/graphql/modules/cycle/requests/cycle-update.request.ts
src/interface/graphql/modules/user/user.resolver.ts

* [`execution-mode#273`](https://github.com/budproj/execution-mode/pull/273)

feat(cycle-management): structuring get cycle, update cycle and delete

---

package.json
waypoint.hcl

ci(waypoint): deploy script with github token

---

src/core/ports/commands/get-team-tactical-cycle.command.ts

Consider only active cycles.
* [`BUD22-398`](https://getbud.atlassian.net/browse/BUD22-398)

fix(tactical-cycle): consider only active cycles

---

src/interface/graphql/modules/team/objects/team-create-input.object.ts
src/interface/graphql/modules/team/objects/team-update-input.object.ts
src/interface/graphql/modules/team/requests/team-update.request.ts
src/interface/graphql/modules/team/team.access-control.ts
src/interface/graphql/modules/team/team.resolver.ts

Creating a mutation that edits a team.
Creating the updateTeam command and the update team mutation.
Editing a team using a mutation, using "updateTeam" method via graphql studio.
- [`BUD22-419`](https://getbud.atlassian.net/jira/software/projects/BUD22/boards/16?assignee=6221193315521d00726b288c&selectedIssue=BUD22-419)

feat(update-team): creating update team mutation

---

src/interface/graphql/modules/team/objects/team-update-input.object.ts

The creation of a mutation that edits a team.
The mutation creation.
Use the mutation updateTeam.
- [`execution-mode#302`](https://github.com/budproj/execution-mode/pull/302)

feat(edit-team): edit team modal and leader tag done

---

manifests/stable/deployment.yaml

chore(debug): enable debug for backend

---

src/core/core.module.ts
src/core/core.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-user-with-teams-from-sub.command.ts
src/core/ports/commands/verify-token.command.ts
src/infrastructure/authz/authz.module.ts
src/infrastructure/authz/providers/jwt.provider.ts
src/interface/tasks/tasks.controller.ts
src/interface/tasks/tasks.module.ts

See pending routines on notification modal
Get pending routines from the backend
Open the application and you should see the routine if the company has a routine setted
- [`BUD22-438`](https://getbud.atlassian.net/browse/BUD22-438)
- [`execution-mode#316`](https://github.com/budproj/execution-mode/pull/316)
- [`routines-microservice#11`](https://github.com/budproj/routines-microservice/pull/11)

feat(routines): implements pending routines

---

src/core/modules/team/team.provider.ts

Revert "fix(getRooTeam): prevent circular dependency"

---

src/core/modules/team/team.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-team-members.command.ts
src/core/ports/commands/get-users-from-team.command.ts

Creating a command to send user infos to routines microservice
Creating a command that activates another command
Using get team users command
- x
- x

feat(user-team-port): creating user team port to routine microservice

---

.env.example
bin/install.sh
manifests/canary/canary-deployment.yaml
manifests/stable/deployment.yaml
src/config/amplitude/amplitude-environment.schema.ts.ts
src/config/amplitude/amplitude.config.ts
src/config/amplitude/amplitude.interface.ts
src/config/amplitude/amplitude.module.ts
src/config/amplitude/amplitude.provider.ts
src/core/modules/user/user.module.ts
src/core/modules/user/user.provider.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-user-last-access.command.ts
src/infrastructure/amplitude/adapters/user-profil.adapter.ts
src/infrastructure/amplitude/amplitude.module.ts
src/infrastructure/amplitude/providers/user-profile.provider.ts
src/infrastructure/amplitude/types/user-profile.data.ts
src/infrastructure/infrastructure.module.ts
src/infrastructure/orm/migrations/1659633494216-goal-currency.ts
src/interface/graphql/modules/user/objects/user-amplitude-data-object.ts
src/interface/graphql/modules/user/user.resolver.ts

feat(last-access): adding last access of amplitude to the user resolver

---

src/interface/graphql/modules/key-result/connections/key-result-timeline/key-result-timeline-entry.union.ts

bugfix(graphql/kr/timeline): timeline not loading

---

src/interface/graphql/helpers/get-resolved-fields-in-edges-and-nodes.helper.ts

fix(get-team-members) fix permission to create a new team

---

src/core/ports/commands/base-status.command.ts

fix(user-indicators): fixing up to date checkins in user status

---

src/interface/graphql/helpers/get-resolved-fields-in-edges-and-nodes.helper.ts

fix(create-team)  fix permission to create a new team

---

src/core/modules/cycle/cycle.provider.ts
src/core/ports/commands/get-team-tactical-cycle.command.ts

fix(tactical-cycle): adding quarterly filter to tactical cycle

---

bin/install.sh

bugfix(bin/install): automatic creating docker network if doesn't exists

---

src/core/ports/commands/get-team-score.command.ts

fix(team-score): adding total to the score count

---

src/core/modules/key-result/check-mark/key-result-check-mark.provider.ts
src/core/ports/commands/base-status.command.ts

fix(indicators): adding all check lists

---

.env.example
manifests/stable/deployment.yaml
src/config/typeorm/typeorm-cli.config.ts
src/config/typeorm/typeorm-environment.schema.ts
src/config/typeorm/typeorm.config.ts
src/config/typeorm/typeorm.interface.ts
src/config/typeorm/typeorm.provider.ts

feat(connection-pool): adding config to the core and yaml

---

manifests/stable/deployment.yaml

fix(connection-pool): increasing to 40

---

manifests/canary/canary-deployment.yaml
src/config/typeorm/typeorm-cli.config.ts
src/config/typeorm/typeorm.config.ts
src/config/typeorm/typeorm.interface.ts
src/config/typeorm/typeorm.provider.ts
src/infrastructure/orm/typeorm.factory.ts

config(typeorm): fix poolSize configuration

---

manifests/canary/canary-deployment.yaml
manifests/stable/deployment.yaml

config(typeorm): decrease poolSize configuration

---

.env.example
manifests/canary/canary-deployment.yaml
manifests/stable/deployment.yaml
src/config/typeorm/typeorm-cli.config.ts
src/config/typeorm/typeorm-environment.schema.ts
src/config/typeorm/typeorm.config.ts
src/config/typeorm/typeorm.interface.ts
src/infrastructure/orm/typeorm.factory.ts

config(typeorm): set pool timeout (idleTimeout) for canary and stable releases

---

src/core/entity.provider.ts
src/core/modules/team/team.provider.ts
src/core/modules/user/user.provider.ts
src/core/ports/commands/base-status.command.ts
src/core/ports/commands/get-users-from-team.command.ts

fix(user): fix sorting in getUsersByTeams

---

src/core/modules/user/user.provider.ts

fix(user): fix dump error in user.provider

---

manifests/stable/deployment.yaml

config(typeorm): decrease max connection pool size from 90 to 70

---

lib/cache/cacheable.decorator.ts

This reverts commit 42ff8bed4372a5bf9a6fb03ad55382b4596f94a5.

Revert "Fix/cacheable compression (#261)"

---

src/infrastructure/analytics/analytics.provider.ts

feat(analytics): add logs to analytics module

---

src/infrastructure/notification/notification.provider.ts
src/interface/tasks/tasks.controller.ts

config(logs): add logs to notification ports

---

package-lock.json
src/core/ports/commands/check-if-user-has-pending-key-results.command.ts
src/core/ports/commands/get-key-result-status.command.ts
src/core/ports/commands/get-user-key-results.command.ts
src/infrastructure/notification/notifications/pending-tasks.notification.ts

fix(routines): fix routines notifications

---

src/core/ports/commands/get-team-objectives.command.ts
src/core/ports/commands/get-team-support-objectives.command.ts
src/interface/graphql/modules/team/team.resolver.ts

feat(team): add extra logging to team objectives commands

---

package-lock.json
src/core/modules/key-result/key-result.provider.ts
src/core/ports/commands/get-cycle-status.command.ts
src/core/ports/commands/get-team-status.command.ts
src/core/ports/commands/get-user-quarterly-progress.command.ts
src/core/ports/commands/get-user-yearly-progress.command.ts

fix(progress): removing draft mode keyresults from progresses

---

package-lock.json
package.json
prisma/migrations/20230713215036_openaicompletion_rename_tokens_columns/migration.sql
prisma/schema.prisma
src/llm/domain/open-ai/dtos/create-key-result-completion.dto.ts
src/llm/domain/open-ai/services/open-ai-completion.service.ts
src/llm/infra/http/controllers/llm.controller.ts
src/llm/shared/utilities/generate-id.ts
src/llm/shared/utilities/summarize-key-result-prompt-builder.ts
src/llm/shared/utilities/summarize-key-result.types.ts
src/llm/shared/utilities/types.ts

feat(llm): upgrade key result summary prompt to v1.1

---

src/llm/domain/open-ai/services/open-ai-completion.service.ts
src/llm/infra/http/controllers/llm.controller.ts
src/llm/shared/utilities/summarize-key-result-prompt-builder.ts

feat(llm): upgrade key result summary prompt to v2.0

---

src/llm/infra/http/DTOs/create-completion-body.ts
src/llm/infra/http/controllers/llm.controller.ts
src/llm/shared/utilities/summarize-key-result-prompt-builder.ts

Feat/llm summarize key result v2.1

---

src/llm/shared/utilities/summarize-key-result-prompt-builder.ts

fix(llm): handle key results no check-ins

---

src/adapters/confidence-tag/confidence-tag.constants.ts
src/adapters/confidence-tag/confidence-tag.enum.ts
src/core/modules/key-result/key-result.provider.ts
src/core/ports/commands/base-status.command.ts
src/interface/graphql/modules/user/connections/user-teams/requests/quantity-request.ts
src/interface/graphql/modules/user/connections/user-teams/user-teams.resolver.ts

feat(new-kr-confidences): adding confidences

---

src/infrastructure/notification/notifications/created-key-result-check-in.notification.ts
src/interface/graphql/adapters/activity/dispatch-response-to-activity.interceptor.ts
src/mission-control/domain/tasks/services/assigner-task.service.ts
src/mission-control/domain/tasks/services/fullfilker-task.service.ts
src/mission-control/domain/tasks/services/task-planner.service.ts
src/mission-control/domain/tasks/use-cases/assign-task/assign-comment-on-key-result.ts
src/mission-control/domain/tasks/use-cases/assign-task/assign-empty-description-key-result-task.ts
src/mission-control/infra/database/postgresjs/repositories/core-domain.repositorie.ts
src/mission-control/infra/messaging/messaging.module.ts
src/mission-control/infra/messaging/producers/task-creation.producer.ts
src/mission-control/jobs/assign-tasks.job.ts

fix(mission-control): fix task assignments

---

prisma/mission-control/migrations/20230927012801_/migration.sql
prisma/mission-control/migrations/20230927013607_create_task_table_index/migration.sql
prisma/mission-control/schema.prisma
src/mission-control/domain/tasks/repositories/task-repositoriy.ts
src/mission-control/domain/tasks/use-cases/fulfill-task/fullfil-comment-on-key-result-task.ts
src/mission-control/infra/database/prisma/repositories/task.repositorie.ts
src/mission-control/jobs/assign-tasks.job.ts

fix fullfil kr-comment and remove onAppBootstrap cron

---

src/mission-control/domain/tasks/services/assigner-task.service.ts
src/mission-control/infra/database/postgresjs/repositories/core-domain.repositorie.ts
src/mission-control/jobs/assign-tasks.job.ts

apply filters and regenerate tasks by confidence

---

src/mission-control/domain/tasks/services/assigner-task.service.ts
src/mission-control/jobs/assign-tasks.job.ts

fix(assignment-tasks) add all tasks to assign-tasks-services

---

src/interface/graphql/adapters/authorization/resolvers/permissions.resolver.ts
src/interface/graphql/modules/objective/connections/objectives/objectives.resolver.ts
src/interface/graphql/modules/user/connections/users/users.resolver.ts

Revert "Feat/private pdi"

---

manifests/canary/canary-jobs.yaml

fix(jobs): update api version from v1beta1 to v1

---

src/core/modules/key-result/key-result.provider.ts

fix: refactor KeyResultProvider's totalCount assignmen

---

src/infrastructure/orm/migrations/1706189188117-AddActiveCycleViews.ts

feat: add views to optimize queries

---

src/core/ports/commands/get-objectives-and-key-results-quantities.command.ts

perf: rewrite and optimize get-objectives-and-key-results-quantities command

---

src/core/modules/user/user.interface.ts
src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-user-key-results-statuses-with-checkmarks.command.ts
src/core/ports/commands/get-user-key-results-statuses.command.ts
src/core/ports/commands/get-user-teams.command.ts
src/interface/graphql/modules/key-result/key-result.node.ts
src/interface/graphql/modules/team/team.node.ts
src/interface/graphql/modules/user/user.node.ts
src/interface/graphql/modules/user/user.resolver.ts

perf(query): unify get users teams and company into a single query

---

src/core/ports/commands/get-team-ranked-descendants.ts
src/interface/graphql/modules/team/team.resolver.ts

refactoring get company teams query

---

src/core/ports/commands/get-team-ranked-descendants.ts
src/interface/graphql/modules/team/team.resolver.ts

Revert "refactoring get company teams query"

---

src/core/ports/commands/get-team-ranked-descendants.ts

fixing delta and tactical cycle

---

src/core/ports/commands/get-team-ranked-descendants.ts

fixing status bug

---

src/config/typeorm/typeorm-cli.config.ts
src/config/typeorm/typeorm.config.ts
src/config/typeorm/typeorm.interface.ts
src/infrastructure/orm/typeorm.factory.ts

Feat: read replica.

---

src/adapters/authorization/godmode/decorators/god-bypass.decorator.ts
src/core/ports/commands/get-team-tree.command.ts
src/core/ports/commands/get-users-from-team.command.ts
src/interface/graphql/adapters/authorization/guards/required-policies.guard.ts
src/interface/graphql/modules/user/user.resolver.ts
src/interface/graphql/modules/workspace/workspace.resolver.ts

removing loggers

---

src/core/ports/commands/command.factory.ts
src/core/ports/commands/get-objectives-and-key-results-quantities.command.ts
src/core/ports/commands/get-team-progress-with-children.command.ts
src/interface/graphql/modules/team/team.resolver.ts

adding new progress with children and new quantites with children

---

src/interface/graphql/modules/user/user.resolver.ts

removing cache

---

src/core/ports/commands/get-objectives-and-key-results-quantities.command.ts

Fix: OKR quantities.
